name:              buttress
version:           0.0.1

ghc-options: -Wall -fwarn-tabs

dependencies:
  - base                          >= 4          && < 5
  - time

library:
  source-dirs: src
  exposed-modules:
    - Buttress
    - Buttress.Time
